[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/qr"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true

[[redirects]]
  from = "/qr/*"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"